name: beaver

executable:
  source-dirs: .
  main: Run.hs

dependencies:
- array
- base
- containers
- mtl
- time

language: GHC2021

default-extensions:
- BlockArguments
- LambdaCase

ghc-options: -O2
